### ISSUE TITLE
Add `Zipper.*_within` APIs that operate on subtrees

### ISSUE THREAD

**Issue by zachallaun** [doorgan/sourceror#134]
Currently, regardless of the focus of a zipper, functions like `Zipper.find/2` will continue to search nodes *outside* of the focus (depth-first pre-order). There are cases where it's useful to operate only within the bounds of the current focus, however.

For instance:

```elixir
zipper
|> Zipper.find(...) # find some parent node
|> Zipper.find_within(...) # find some child within the parent node
|> Zipper.update(...) # update the child somehow
|> Zipper.root() # navigate back to the root of the entire AST
```

There are other functions in `Zipper`, like `traverse`, that would also benefit from a `*_within` variant.

**Comment by NickNeck** [comment]
That sounds like a good idea, @zachallaun. 

The `traverse` functions already operate on the subtree, so they do not need the `*_within` version.

Perhaps we could also simply introduce an `within/2` function.
```elixir
zipper
|> Zipper.find(...) # find some parent node
|> Zipper.within(fn z -> Zipper.find(z, ...)) # find some child within the parent node
|> Zipper.update(...) # update the child somehow
|> Zipper.root() # navigate back to the root of the entire AST
```
