### ISSUE TITLE
Proposal: Zipper function to break out single subtree level

### ISSUE THREAD

**Issue by zachallaun** [doorgan/sourceror#168]
We currently have `top`, which moves to the top of the current subtree (but doesn't break out of it), and `topmost`, which moves to the very top of the Zipper, breaking out of all subtrees. What we don't have is a function that moves to the top of the current subtree *and* breaks out of it.

This would be really nice. It would let you create a subtree, move within and modify it in the context of that subtree, and then jump back to where you started.

**Comment by zachdaniel** [comment]
Right, so maybe `Zipper.supertree(zipper) :: nil | zipper`?

**Comment by doorgan** [comment]
Sounds useful, let's add it
@zachdaniel suggesion for the name sounds good to me, we already have `subtree` and this new function would do the opposite. Supertree is also the same concept we use in the implementation

**Comment by zachallaun** [comment]
Where should this stand with regards to #166? Should `Zipper.supertree(nil)` return `nil` or blow up?

**Comment by zachdaniel** [comment]
🤔 I think blow up? Wouldn't hurt to start with blowing up I think, can always make it return `nil` until later.

**Comment by doorgan** [comment]
Merged with #167
