### ISSUE TITLE
Allow `Sourceror.to_string` to format keyword list elements as list elements and not as tuples

### ISSUE THREAD

**Issue by doorgan** [doorgan/sourceror#18]
If the user wants to patch the code to rename an option in a keyword list, they would only need to format a single element of the list. The problem is that an element of a keyword list is a 2-tuple, and even if the Formatter knows how to handle the `format: :keyword` metadata, if the tuple is not inside of a list, this rule is ignored:
```elixir
iex> {_, _, [[tuple]]} = Sourceror.parse_string!("[a: b]")
iex> Sourceror.to_string(tuple)
"{:a, b}"
```

So the user needs to wrap the element in a list and then strip the brackets to get the desired output:
```elixir
iex> {_, _, [[tuple]]} = Sourceror.parse_string!("[a: b]")
iex> Sourceror.to_string([tuple], format: :keyword) |> String.slice(1..-2)
"a: b"
```
This is tedious, an forces the user to think about how the formatter works to get the output they want.

One way to solve this would be to add a `format: :keyword` option to `Sourceror.to_string/2`, so that it will format a 2-tuple as if it were inside of a list:
```elixir
iex> {_, _, [[tuple]]} = Sourceror.parse_string!("[a: b]")
iex> Sourceror.to_string(tuple, format: :keyword)
"a: b"
```
If the user wants to do the same for multiple tuples, it would work with a list too:
```elixir
iex> {_, _, [[tuple]]} = Sourceror.parse_string!("[a: b]")
iex> Sourceror.to_string([tuple, tuple], format: keyword)
"a: b, a: b"
```
The problem with this use case is that it would also work with other kinds of lists, for example:
```elixir
iex> Sourceror.to_string([1, 2, 3], format: :keyword)
"1, 2, 3"
```
So in this case the behavior is not the same as having `format: :keyword` metadata, but it's more like `format: :splicing` (borrowing the term from the behavior of `unquote_splicing`).

So if this were to be added, we have to decide which name for the option makes the most sense.

Moreover, it may be worth considering the case of a regular 2-tuple like `{:a, :b}`(ie not a wrapped literal). Sourceror is able to print this thanks to `Code.quoted_to_algebra`, but since the key is not a wrapped atom with the `format: :keyword` metadata, it can't be printed as a keyword list element. So, would it make sense to also introduce a function like `Sourceror.build_kw_element(key, value)`?

**Comment by msaraiva** [comment]
The `:splicing` format sounds like a good idea. We could also have somethig like:

```elixir
# No format
iex> Sourceror.to_string("[a: 1, b: 2]")
"[{:a, 1}, {:b, 2}]"

# Format :keyword
iex> Sourceror.to_string("[a: 1, b: 2]", format: :keyword)
"[a: 1, b: 2]"

# Format :keyword_options
iex> Sourceror.to_string("[a: 1, b: 2]", format: :keyword_options)
"a: 1, b: 2"
```

One problem is that using `:keyword_options` would only generate valid code if the kw list is the last argument of a function or the last item of a list/tuple. 

Maybe the only way to get this right would be to create specific functions to handle kw "options". A function receiving the whole quoted expression (function, tuple or list) would be able to check the last item/argument and replace it accordingly (I guess). Something like `Sourceror.patch_keyword_option(:the_option, ...)`.

Is your intention to provide a higher level API to patch common fragments? Like `Sourceror.rename_function(...)`, `Sourceror.patch_function_arg(..., arg_index)`, `Sourceror.remove_function_arg(..., arg_index)` and so on? If so, it could be an option.

Either way, I think what you've already achieved is pretty awesome 🙂

**Comment by doorgan** [comment]
Hi @msaraiva!

The issue I have with the name `:keyword_options` is that you can also use it to update Ecto queries or stuff after the `when` in typespecs.

> One problem is that using `:keyword_options` would only generate valid code if the kw list is the last argument of a function or the last item of a list/tuple.

The case for `to_string generating something like `a: b, :not_an_option, c: d` was just fixed in elixir master, it was a bug in the Elixir.Normalizer :slightly_smiling_face: 

> Maybe the only way to get this right would be to create specific functions to handle kw "options". A function receiving the whole quoted expression (function, tuple or list) would be able to check the last item/argument and replace it accordingly (I guess). Something like `Sourceror.patch_keyword_option(:the_option, ...)`.

I'm not sure about this, because it's not clear if it should return a patch, a string, or a new ast. Actually I think that just using `format: :splicing` and making the user wrap a single tuple in a list as to not add an additional special case would be enough for the simple case of replacing elements from a keyword list. WDYT?

> Is your intention to provide a higher level API to patch common fragments? Like `Sourceror.rename_function(...)`, `Sourceror.patch_function_arg(..., arg_index)`, `Sourceror.remove_function_arg(..., arg_index)` and so on? If so, it could be an option.

I've been playing with the idea of providing an API to build nodes from literals, something like `Sourceror.Nodes.build_block(:do, contents)` or `Sourceror.Nodes.build_literal("hello!")`, or adding functions like `Sourceror.has_block?(quoted, :catch)` or `Sourceror.get_block(quoted, :else)` to ease the pain of getting a particular block from a function, but I didn't thought about an API for creating common patch fragments. I can see the utility, and it's something worth considering, but I would like to get a better understanding of the use cases first :slightly_smiling_face:. A proposal is very much welcome, though!

**Comment by msaraiva** [comment]
> I think that just using `format: :splicing` and making the user wrap a single tuple in a list as to not add an additional special case would be enough for the simple case of replacing elements from a keyword list. WDYT?
> 
> >

I totally agree.

> I didn't thought about an API for creating common patch fragments. I can see the utility, and it's something worth considering, but I would like to get a better understanding of the use cases first 🙂. A proposal is very much welcome, though!

I think you don't have to consider adding such API now. It's better to wait for feedback and see the real cases people will be using this lib. As I said, it already makes it possible implementing ALL cases I had so I'd just focus on making it stable for now and then consider adding new features later 🙂.

**Comment by doorgan** [comment]
> It's better to wait for feedback and see the real cases people will be using this lib.
> I'd just focus on making it stable for now and then consider adding new features later :slightly_smiling_face:.

Sounds very reasonable :slightly_smiling_face:
Thanks for your thoughts!

**Comment by doorgan** [comment]
Hey @msaraiva! Just a heads up, but I ended up adding a `Sourceror.Patch` module, as I found myself needing that as well. Functions from that module take AST and return a list of patches, and includes a `rename_call` that you can use even with sigils, and `rename_kw_keys` for the options.

**Comment by msaraiva** [comment]
Wow! That's really nice 🔥 🔥 🔥

Thanks for the update!
