### ISSUE TITLE
Removing current node failing

### ISSUE THREAD

**Issue by juanperi** [doorgan/sourceror#25]
Hey man, I took sourceror for a spin, trying to use the expansion of aliases as a starting point.
I'm hitting a wall when trying to remove the node that i'm expanding. In certain situations it fails. I tried to reproduce just with the zipper, but I couldn't. So i'm surely missing something

Take the following code (based in your code from the notebook, but simplified)
```
defmodule Expander do
  alias Sourceror.Zipper, as: Z

  def run_doesnt_work() do
    """
    defmodule Test do
      alias Test.Repo
      alias Test.{Module, Another}
    end
    """
    |> run()
  end

  def run_works() do
    """
    defmodule Test do
      alias Test.{Module, Another}
      alias Test.Repo
    end
    """
    |> run()
  end

  def run(source) do
    source
    |> Sourceror.parse_string!()
    |> expand()
    |> Sourceror.to_string()
    |> IO.puts()
  end

  def expand(quoted) do
    Z.zip(quoted)
    |> Z.traverse(&expand_alias/1)
    |> Z.root()
  end

  defp expand_alias(
         {{:alias, alias_meta, [{{:., _, [left, :{}]}, call_meta, right}]}, _metadata} = zipper
       ) do
    {_, _, base_segments} = left
    aliases =
      right
      |> Enum.map(&segments_to_alias(base_segments, &1))
      |> Enum.reverse()

    aliases
    |> Enum.reduce(zipper, &Z.insert_right(&2, &1))
    |> Z.remove()
  end

  defp expand_alias(zipper), do: zipper

  defp segments_to_alias(base_segments, {_, meta, segments}) do
    {:alias, meta, [{:__aliases__, [], base_segments ++ segments}]}
  end
end
```

If you run the function `run_works`, it just works 😄 
If you run the function `run_doesnt_work`, it doesnt. The difference is in the order of the aliases that get expanded.
```
iex(153)> Expander.run_works
defmodule Test do
  alias Test.Module
  alias Test.Another
  alias Test.Repo
end
:ok
iex(154)> Expander.run_doesnt_work
** (MatchError) no match of right hand side value: []
    (sourceror 0.8.1) script.exs:184: Sourceror.Zipper.rightmost/1
    (sourceror 0.8.1) script.exs:225: Sourceror.Zipper.prev_after_remove/1
    (sourceror 0.8.1) script.exs:340: Sourceror.Zipper.traverse/2
    script.exs:5: Expander.expand/1
    script.exs:31: Expander.run/1
```

This last function does work if I remove the `Z.remove` though.

Do you have any insight to help me move along with this?

Thank you

**Comment by doorgan** [comment]
Hi there! Thanks for giving Sourceror a try :)

That's a bug in the Zipper implementation, when you remove a node it will try to take a step back. To do that it's calling `Z.down`, and that function pops the first element from the node's children and puts the rest as the right siblings of the zipper.
The issue is that if the node has a single children, then the right siblings will be `[]`, but what defines the end of the siblings is `nil`, so it crashes.

I will push a fix, thanks for finding it!

**Comment by doorgan** [comment]
Version 0.8.2 is out in hex.pm, please let me know if you encounter any other issue :)

**Comment by juanperi** [comment]
Ha! I suspected the bug was in zipper, and tried to reproduce it with a simple array tree, but couldn't find the right case it seems.

Thank you for your prompt response!! seems to be fixed now :)
