### ISSUE TITLE
Comments in pipes moved up

### ISSUE THREAD

**Issue by novaugust** [doorgan/sourceror#27]
Hey hey! Thanks for the great project. 

Had some fun playing with it today, and found that comments in pipes are moved up even if no transformation is done:
```ex
"""
big
|> long()
# comment after long and before chain
|> chain()
"""
|> Sourceror.parse_string!()
|> Sourceror.to_string()
|> IO.puts()
```
results in:
```ex
big
# comment after long and before chain
|> long()
|> chain()
```

this is on current main (4d67ce5b3e795032a4df85266db1cb216841fc20)

**Comment by doorgan** [comment]
Hey there, there's a fix in the main branch for this. If you still encounter more issues don't hesitate to share more examples, these are very much appreciated :)
