### ISSUE TITLE
Module arguments with keyword-list will be reformatted

### ISSUE THREAD

**Issue by NickNeck** [doorgan/sourceror#36]
Hi, here an example tested on master (https://github.com/doorgan/sourceror/commit/e8eaf2c378bac6993e581a7b83d6a79f808c9611)
```elixir
iex(2)> """
...(2)> @foo [
...(2)>   a: 1,
...(2)>   b: 2
...(2)> ]
...(2)> """ |> Sourceror.parse_string!() |> Sourceror.to_string() |> IO.puts()
@foo a: 1,
     b: 2
:ok
```

**Comment by doorgan** [comment]
Hey there! This one was a bug in core Elixir, a fix was already merged and Sourceror's vendored module updated accordingly :)
