### ISSUE TITLE
an FYI - the transformation i've been building up to running across the codebase :)

### ISSUE THREAD

**Issue by novaugust** [doorgan/sourceror#42]
https://gist.github.com/novaugust/3f7b75f922ba3b137093913ad29b9d88

**Comment by novaugust** [comment]
It's worked terrifically. Only things I'd consider building on top of it:

- rewrite `foo(bar) |> baz` to `bar |> foo |> baz` (currently does `baz(foo(bar))`
- condense all rewrites into a single line function call if possible (i assume this would involve playing w/ meta line numbers)

**Comment by doorgan** [comment]
That's cool!

Yup, to condense everything into a single line you'd need to traverse the expression and replace the line numbers with the line number of the leftmost node(in this case `foo`). If any of the line numbers is higher, the formatter will most probably format it as a vertical pipeline. Something like this:
```elixir
# Postwalk
Macro.postwalk(pipeline_ast, fn quoted -> Macro.update_meta(quoted, &Keyword.put(&1, :line, line_number) end)

# Zipper
Zipper.traverse(zipper,  fn {quoted, ctx} -> {Macro.update_meta(quoted, &Keyword.put(&1, :line, line_number), ctx} end)
```

> `# i feel convinced i need fun_meta for some case but haven't found it yet!`

Yup, in this case it would be a rare edge case, you'd need some code like this for it to "break":
```elixir
# First comment
foo
|>
# Second comment
bar()
```
The second comment will be lost, so you'd probably have to move it to `foo`, or move `foo`'s comments to `bar` and discard `foo`'s meta. This kind of situation is always kind of tricky, but for this particular case I'd say its rare enough to not be concerned about.

**Comment by novaugust** [comment]
collected my two transformations in this gist:
https://gist.github.com/novaugust/badfb2a1fe1c7de2d7c76b31b046dafa

**Comment by doorgan** [comment]
Wow that's awesome! I'm glad it worked out nicely :D
